{% set name = "kalpy" %}
{% set version = "0.6.7" %}

package:
  name: kalpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kalpy-kaldi/kalpy_kaldi-{{ version }}.tar.gz
  sha256: b3b41363e7fd1a1dabe14a6981353157013b8e5e34e0666c1440e4463e4d61de

build:
  number: 0
  run_exports:
    strong:
      - kalpy

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - setuptools                                # [build_platform != target_platform]
    - setuptools_scm                            # [build_platform != target_platform]
    - cmake
    - make                                      # [not win]
    - ninja
    - pybind11
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - kaldi =*=cpu*
    - openfst ==1.8.3
    - pynini ==2.1.6
  run:
    - python
    - dataclassy
    - numpy
    - librosa
    - praatio
    - openfst ==1.8.3
    - pynini ==2.1.6
  run_constrained:
    - kaldi =*=cpu*

about:
  home: https://github.com/mmcauliffe/kalpy
  summary: 'Pybind11 bindings for Kaldi for use with the Montreal Forced Aligner'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mmcauliffe/kalpy
  dev_url: https://github.com/mmcauliffe/kalpy

extra:
  recipe-maintainers:
    - mmcauliffe
